### PR TITLE
add Led.RGB example

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
Add an example using the PWM pins and the Johnny five `LED.RGB` class.

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
- [ ] Fix failing build
- [ ] Add fritzing

**Comment by rwaldron** [comment]
Nice, I'll do a full review and get this landed tomorrow ❤️

**Comment by LongLiveCHIEF** [comment]
@rwaldron You ever get a chance to look at this?

**Comment by rwaldron** [comment]
Sorry, I was away on parental leave and I'm still catching up! I appreciate your patience

**Pull request merged**
